// let newdate = new Date();
// // console.log(newdate.getFullYear());
// // console.log(newdate.getMonth());
// // console.log(newdate.getDate());
// // console.log(newdate.getHours());
// // console.log(newdate.getMinutes());
// // console.log(newdate.getSeconds());
// // console.log(newdate.getMilliseconds());
// // console.log(newdate.getDay());
// console.log(newdate.getTime());
// console.log(newdate.getTimezoneOffset());
// console.log(newdate.toDateString());
// console.log(newdate.toTimeString());
// console.log(newdate.toLocaleString());
// console.log(newdate.toLocaleDateString());
// console.log(newdate.toLocaleTimeString());
// console.log(newdate.toString());
// console.log(newdate.toUTCString());
// console.log(newdate.toISOString());
// console.log(newdate.toJSON());
// console.log(newdate.valueOf());
// console.log(newdate.toUTCString());


// let newdate = new Date();
// console.log(newdate.getFullYear());
// var a = "a";
// console.log(typeof(a));
let age = 23;
if (age > 18) console.log(true);
